# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappingpedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionprogress',
            name='result_page',
            field=models.URLField(default=b'', max_length=250),
        ),
        migrations.AddField(
            model_name='executionprogress',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 14, 8, 11, 103678)),
        ),
        migrations.AddField(
            model_name='executionprogress',
            name='user',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
