# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappingpedia', '0002_auto_20180214_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionprogress',
            old_name='result_page',
            new_name='result_url',
        ),
        migrations.AlterField(
            model_name='executionprogress',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 15, 0, 54, 799127)),
        ),
    ]
